# -*- coding: utf-8 -*-
"""GBTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XYKOg3co7h_SfKIGBb_6EDmt-PKpq3V
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

# ── All imports ──
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['figure.dpi'] = 100
import warnings
warnings.filterwarnings('ignore')

import statsmodels.formula.api as smf
from statsmodels.regression.mixed_linear_model import MixedLM
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

import pandas as pd

# Load the .dta file
wide_data = pd.read_stata('wide_data_clpm.dta')

import pandas as pd

# Load the .dta file
long_data = pd.read_stata('long_data_clpm.dta')

# Check
print("Wide data shape:", wide_data.shape)
print("Long data shape:", long_data.shape)
print("\nWide data columns:", list(wide_data.columns))
print("\nFirst few rows:")
print(wide_data[['pidp','ghq1','ghq2','ghq3','ghq4','ghq5',
                  'slp1','slp2','slp3','slp4','slp5']].head())

print("Wide data shape:", wide_data.shape)
print("Long data columns:", list(long_data.columns[:10]))

# Fix id column — check what the person ID column is called
print("\nLong data columns:", list(long_data.columns))

if 'id' not in long_data.columns and 'pidp' in long_data.columns:
    long_data['id'] = pd.factorize(long_data['pidp'])[0] + 1
    print("Created id from pidp")

wave_labels = ['W1\n(2009)', 'W2\n(2012)', 'W3\n(2015)',
               'W4\n(2018)', 'W5\n(2021)']
x_pos = [0, 1, 2, 3, 4]   # numeric positions for fill_between

ghq_cols = ['ghq1','ghq2','ghq3','ghq4','ghq5']
slp_cols = ['slp1','slp2','slp3','slp4','slp5']

# ── Compute means, SE, 95% CI ──────────────────────────────────
def get_stats(data, cols):
    means  = [data[c].mean()  for c in cols]
    sds    = [data[c].std()   for c in cols]
    ns     = [data[c].count() for c in cols]
    ses    = [sd / np.sqrt(n) for sd, n in zip(sds, ns)]
    lower  = [m - 1.96*se    for m, se  in zip(means, ses)]
    upper  = [m + 1.96*se    for m, se  in zip(means, ses)]
    return means, lower, upper

ghq_means, ghq_lower, ghq_upper = get_stats(wide_data, ghq_cols)
slp_means, slp_lower, slp_upper = get_stats(wide_data, slp_cols)

print("GHQ means:",   [round(m,3) for m in ghq_means])
print("Sleep means:", [round(m,3) for m in slp_means])

# ── Shared style settings ──────────────────────────────────────
FONT_FAMILY  = 'DejaVu Sans'
TITLE_SIZE   = 15
SUBTITLE_SIZE= 9
LABEL_SIZE   = 11
TICK_SIZE    = 10
ANNOT_SIZE   = 10
CAPTION_SIZE = 9

def style_ax(ax):
    """Apply the clean publication style to an axes object."""
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#CCCCCC')
    ax.spines['bottom'].set_color('#CCCCCC')
    ax.tick_params(colors='#444444', labelsize=TICK_SIZE)
    ax.yaxis.grid(True, color='#E5E5E5', linewidth=0.8, zorder=0)
    ax.set_axisbelow(True)
    ax.xaxis.grid(False)

# ══════════════════════════════════════════════════════════════
# GRAPH 2 — GHQ-12
# ══════════════════════════════════════════════════════════════

ghq_cols = ['ghq1','ghq2','ghq3','ghq4','ghq5']
slp_cols = ['slp1','slp2','slp3','slp4','slp5']

# Calculate mean and SD
ghq_means = [wide_data[c].mean() for c in ghq_cols]
ghq_sds   = [wide_data[c].std()  for c in ghq_cols]
slp_means = [wide_data[c].mean() for c in slp_cols]
slp_sds   = [wide_data[c].std()  for c in slp_cols]

fig, ax = plt.subplots(figsize=(9, 5.5))
ax.errorbar(wave_labels, ghq_means,
            color='#3C3489', linewidth=2,
            marker='o', markersize=1,
            capsize=5, capthick=1.5,
            elinewidth=1.5,
            label='Mean ± SD')

for x, (m, s) in enumerate(zip(ghq_means, ghq_sds)):
    ax.annotate(f'{m:.2f}±{s:.2f}',
                (wave_labels[x], m),
                textcoords="offset points",
                xytext=(-6, 15), ha='center',
                fontsize=9, color='#3C3489', fontweight='semibold')

ax.fill_between(x_pos, ghq_lower, ghq_upper,
                alpha=0.15, color='#3C3489', zorder=1)

ax.plot(x_pos, ghq_means,
        color='#3C3489', linewidth=2.2,
        marker='o', markersize=10,
        markerfacecolor='#3C3489', markeredgecolor='white',
        markeredgewidth=1.5, zorder=3)



# Tight y-axis for GHQ too
y_min = min(ghq_lower) - 0.05
y_max = max(ghq_upper) + 0.15
ax.set_ylim(y_min, y_max)
ax.yaxis.set_major_locator(ticker.MultipleLocator(0.2))
ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.1f'))

ax.set_xticks(x_pos)
ax.set_xticklabels(wave_labels, fontsize=TICK_SIZE, color='#444444')
ax.set_xlim(-0.35, 4.35)

style_ax(ax)
ax.spines['left'].set_color('black')
ax.spines['bottom'].set_color('black')

ax.set_xlabel('Survey Wave', fontsize=14,
              color='#333333', labelpad=8)
ax.set_ylabel('Mean GHQ-12 Score (0–36)',
              fontsize=14, color='#333333', labelpad=8)

ax.set_title('Mean GHQ-12 Score Across Five Waves',
             fontsize=TITLE_SIZE, fontweight='bold',
             color='#1A1A1A', pad=8, loc='left')


fig.text(0.98, 0.02,
         'Error bands represent 95% confidence intervals.\n'
         'Higher scores indicate worse general health.',
         ha='right', va='bottom',
         fontsize=CAPTION_SIZE, color='#888888',
         linespacing=1.5)

plt.tight_layout(rect=[0, 0.04, 1, 0.96])
plt.savefig('ghq_line_graph_pub.png', dpi=300, bbox_inches='tight',
            facecolor='white')
plt.show()
print("Saved: ghq_line_graph_pub.png")

# ══════════════════════════════════════════════════════════════
# GRAPH 1 — Sleep Quality
# ══════════════════════════════════════════════════════════════
fig, ax = plt.subplots(figsize=(9, 5.5))

ax.errorbar(wave_labels, slp_means,
            color='#3C3489', linewidth=2,
            marker='o', markersize=8,
            capsize=5, capthick=1.5,
            elinewidth=1.5,
            label='Mean ± SD')

for x, (m, s) in enumerate(zip(slp_means, slp_sds)):
    ax.annotate(f'{m:.2f}±{s:.2f}',
                (wave_labels[x], m),
                textcoords="offset points",
                xytext=(0, 14), ha='center',
                fontsize=9, color='#0F6E56', fontweight='semibold')

# CI band
ax.fill_between(x_pos, slp_lower, slp_upper,
                alpha=0.18, color='#0F6E56', zorder=1)

# Line + markers
ax.plot(x_pos, slp_means,
        color='#0F6E56', linewidth=2.2,
        marker='o', markersize=10,
        markerfacecolor='#0F6E56', markeredgecolor='white',
        markeredgewidth=1.5, zorder=3)


# ── Y-axis: tight range around the actual data ─────────────────
y_min = min(slp_lower) - 0.01
y_max = max(slp_upper) + 0.03
ax.set_ylim(y_min, y_max)

# Fine-grained ticks so the small variation is visible
import matplotlib.ticker as ticker
ax.yaxis.set_major_locator(ticker.MultipleLocator(0.02))
ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.2f'))

# X-axis
ax.set_xticks(x_pos)
ax.set_xticklabels(wave_labels, fontsize=14, color='#444444')
ax.set_xlim(-0.35, 4.35)

style_ax(ax)
ax.spines['left'].set_color('black')
ax.spines['bottom'].set_color('black')
# Labels
ax.set_xlabel('Survey Wave', fontsize=14,
              color='#333333', labelpad=8)
ax.set_ylabel('Mean Sleep Quality Score (1–4)',
              fontsize=14, color='#333333', labelpad=8)

# Title block (title + subtitle like the uploaded graph)
ax.set_title('Mean Sleep Quality Score Across Five Waves',
             fontsize=TITLE_SIZE, fontweight='bold',
             color='#1A1A1A', pad=14, loc='left')


# Caption bottom-right (matches uploaded style)
fig.text(0.98, 0.02,
         'Error bands represent 95% confidence intervals.\n'
         'Higher scores indicate worse sleep quality.',
         ha='right', va='bottom',
         fontsize=CAPTION_SIZE, color='#888888',
         linespacing=1.5)

plt.tight_layout(rect=[0, 0.04, 1, 0.96])
plt.savefig('sleep_line_graph_pub.png', dpi=300, bbox_inches='tight',
            facecolor='white')
plt.show()
print("Saved: sleep_line_graph_pub.png")

fig, ax = plt.subplots(figsize=(10, 5.5))

def normalise(vals):
    mn, mx = min(vals), max(vals)
    return [(v - mn) / (mx - mn) for v in vals]

ghq_norm = normalise(ghq_means)
slp_norm = normalise(slp_means)

ax.plot(x_pos, ghq_norm,
        color='#3C3489', linewidth=2.2,
        marker='o', markersize=7,
        markerfacecolor='#3C3489', markeredgecolor='white',
        markeredgewidth=1.5, label='GHQ-12', zorder=3)

ax.plot(x_pos, slp_norm,
        color='#0F6E56', linewidth=2.2,
        marker='s', markersize=7,
        markerfacecolor='#0F6E56', markeredgecolor='white',
        markeredgewidth=1.5, label='Sleep Quality', zorder=3)

ax.set_xticks(x_pos)
ax.set_xticklabels(wave_labels, fontsize=TICK_SIZE, color='#444444')
ax.set_xlim(-0.35, 4.35)
ax.set_ylim(-0.1, 1.15)
ax.yaxis.set_major_locator(ticker.MultipleLocator(0.2))

style_ax(ax)

ax.set_xlabel('Survey Wave', fontsize=LABEL_SIZE,
              color='#333333', labelpad=8)
ax.set_ylabel('Normalised Score (0–1)',
              fontsize=LABEL_SIZE, color='#333333', labelpad=8)

ax.set_title('GHQ-12 and Sleep Quality Trends (Normalised)',
             fontsize=TITLE_SIZE, fontweight='bold',
             color='#1A1A1A', pad=14, loc='left')

fig.text(0.13, 0.93,
         'UKHLS, 2009–2021  (N = 12,875)',
         fontsize=SUBTITLE_SIZE, color='#666666')

ax.legend(fontsize=10, framealpha=0.9,
          edgecolor='#CCCCCC', loc='upper left')

fig.text(0.98, 0.001,
         'Scores normalised to 0–1 for comparability.\n'
         'Higher scores indicate worse outcomes.',
         ha='right', va='bottom',
         fontsize=CAPTION_SIZE, color='#888888',
         linespacing=1.5)

plt.tight_layout(rect=[0, 0.04, 1, 0.96])
plt.savefig('combined_lines_pub.png', dpi=300, bbox_inches='tight',
            facecolor='white')
plt.show()
print("Saved: combined_lines_pub.png")

print("\nAll three graphs saved successfully.")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

wide_data = pd.read_stata('wide_data_clpm.dta')

# ── Select all GHQ and sleep variables ──
vars_ordered = ['ghq1','ghq2','ghq3','ghq4','ghq5',
                'slp1','slp2','slp3','slp4','slp5']

# Friendly labels for the heatmap
labels = ['GHQ W1\n(2009)', 'GHQ W2\n(2012)', 'GHQ W3\n(2015)',
          'GHQ W4\n(2018)', 'GHQ W5\n(2021)',
          'Sleep W1\n(2009)', 'Sleep W2\n(2012)', 'Sleep W3\n(2015)',
          'Sleep W4\n(2018)', 'Sleep W5\n(2021)']

# Compute correlation matrix
corr_matrix = wide_data[vars_ordered].corr()

# ── Print numeric correlation matrix ──
print("=== CORRELATION MATRIX ===")
print(corr_matrix.round(3).to_string())

# ── Heatmap ──
fig, ax = plt.subplots(figsize=(11, 9))

mask = np.zeros_like(corr_matrix, dtype=bool)
mask[np.triu_indices_from(mask, k=1)] = False  # show full matrix

sns.heatmap(
    corr_matrix,
    annot=True,
    fmt='.2f',
    cmap='RdYlGn_r',        # red=high correlation, green=low
    vmin=-0.1, vmax=1.0,
    center=0.3,
    linewidths=0.5,
    linecolor='white',
    xticklabels=labels,
    yticklabels=labels,
    ax=ax,
    annot_kws={"size": 9},
    cbar_kws={"shrink": 0.8,
              "label": "Pearson Correlation Coefficient"}
)

ax.set_title('Correlation Matrix — GHQ-12 and Sleep Quality Across Five Waves',
             fontsize=13, fontweight='bold', pad=15)
ax.tick_params(axis='x', rotation=0, labelsize=9)
ax.tick_params(axis='y', rotation=0, labelsize=9)

# Add a dividing line between GHQ block and Sleep block
ax.axhline(y=5, color='black', linewidth=2.5)
ax.axvline(x=5, color='black', linewidth=2.5)

# Label the two blocks
ax.text(2.5, -0.7, 'GHQ-12', ha='center', va='center',
        fontsize=11, fontweight='bold', color='#3C3489',
        transform=ax.get_xaxis_transform())
ax.text(7.5, -0.7, 'Sleep Quality', ha='center', va='center',
        fontsize=11, fontweight='bold', color='#0F6E56',
        transform=ax.get_xaxis_transform())

plt.tight_layout()
plt.savefig('correlation_heatmap.png', dpi=300, bbox_inches='tight')
plt.show()
print("Correlation heatmap saved")

# Check wave column name
print("Wave column check:")
print([c for c in long_data.columns if 'wave' in c.lower()])

# Make sure time variable exists
long_data['time']  = long_data['wave'] - 1
long_data['time2'] = long_data['time'] ** 2

print("\nLong data head:")
print(long_data[['id','wave','time','ghq','slp']].head(10))
print("\nMissing values:")
print(long_data[['ghq','slp','time','id']].isnull().sum())

import statsmodels.formula.api as smf
from statsmodels.regression.mixed_linear_model import MixedLM

# ── Prepare long data ──
long_data['time'] = long_data['wave'] - 1  # time 0,1,2,3,4
long_data['time2'] = long_data['time'] ** 2  # quadratic term
long_data['id'] = long_data['id'].astype(int)

print("Long data head:")
print(long_data[['id','wave','time','ghq','slp']].head(10))

# ── Linear Growth Curve Model for GHQ ──
print("\n=== Growth Curve Model: GHQ-12 ===")

gcm_ghq = MixedLM.from_formula(
    'ghq ~ time',
    groups = 'id',
    re_formula = '~time',
    data = long_data.dropna(subset=['ghq','time','id'])
)

result_ghq = gcm_ghq.fit(method='lbfgs')
print(result_ghq.summary())

# Extract key parameters
print("\n--- Key GHQ Parameters ---")
print(f"Intercept (mean GHQ at wave 1): {result_ghq.params['Intercept']:.3f}")
print(f"Slope (change per 3-year interval): {result_ghq.params['time']:.3f}")
print(f"Intercept p-value: {result_ghq.pvalues['Intercept']:.4f}")
print(f"Slope p-value: {result_ghq.pvalues['time']:.4f}")

# ── Quadratic Growth Curve Model for GHQ (if linear fits poorly) ──
print("\n=== Quadratic Growth Curve Model: GHQ-12 ===")

gcm_ghq_quad = MixedLM.from_formula(
    'ghq ~ time + time2',
    groups = 'id',
    re_formula = '~time',
    data = long_data.dropna(subset=['ghq','time','time2','id'])
)

result_ghq_quad = gcm_ghq_quad.fit(method='lbfgs')
print(f"Intercept: {result_ghq_quad.params['Intercept']:.3f}")
print(f"Linear slope: {result_ghq_quad.params['time']:.3f}")
print(f"Quadratic term: {result_ghq_quad.params['time2']:.3f}")
print(f"Quadratic p-value: {result_ghq_quad.pvalues['time2']:.4f}")

# Compare AIC
print(f"\nLinear AIC: {result_ghq.aic:.1f}")
print(f"Quadratic AIC: {result_ghq_quad.aic:.1f}")
print("Lower AIC = better fit")

# ── Linear Growth Curve Model for Sleep ──
print("\n=== Growth Curve Model: Sleep Quality ===")

gcm_slp = MixedLM.from_formula(
    'slp ~ time',
    groups = 'id',
    re_formula = '~time',
    data = long_data.dropna(subset=['slp','time','id'])
)

result_slp = gcm_slp.fit(method='lbfgs')
print(result_slp.summary())

print("\n--- Key Sleep Parameters ---")
print(f"Intercept (mean sleep at wave 1): {result_slp.params['Intercept']:.3f}")
print(f"Slope (change per 3-year interval): {result_slp.params['time']:.3f}")
print(f"Slope p-value: {result_slp.pvalues['time']:.4f}")

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# ── Prepare data for GBTM ──
# Use only complete cases across all 5 waves
ghq_data = wide_data[['ghq1','ghq2','ghq3','ghq4','ghq5']].dropna()
slp_data = wide_data[['slp1','slp2','slp3','slp4','slp5']].dropna()

print(f"Complete cases for GHQ GBTM: {len(ghq_data)}")
print(f"Complete cases for Sleep GBTM: {len(slp_data)}")

# ── Find optimal number of groups using BIC-like criterion ──
def compute_bic(kmeans, X):
    centers = kmeans.cluster_centers_
    labels  = kmeans.labels_
    n_clusters = kmeans.n_clusters
    n_samples, n_features = X.shape

    # Compute variance
    variance = np.sum([np.sum((X[labels == k] - centers[k])**2)
                       for k in range(n_clusters)]) / (n_samples - n_clusters)

    # BIC
    bic = (n_samples * np.log(variance) +
           n_clusters * np.log(n_samples) * n_features)
    return bic

print("\n=== GHQ GBTM — Group Comparison ===")
ghq_arr = ghq_data.values
bic_scores_ghq = {}
sil_scores_ghq = {}

for k in range(2, 6):
    km = KMeans(n_clusters=k, random_state=123, n_init=20)
    km.fit(ghq_arr)
    bic_scores_ghq[k] = compute_bic(km, ghq_arr)
    sil_scores_ghq[k] = silhouette_score(ghq_arr, km.labels_)
    print(f"Groups={k}: BIC={bic_scores_ghq[k]:.1f}, Silhouette={sil_scores_ghq[k]:.3f}")

best_k_ghq = min(bic_scores_ghq, key=bic_scores_ghq.get)
print(f"\nOptimal GHQ groups: {best_k_ghq} (lowest BIC)")

print("\n=== Sleep GBTM — Group Comparison ===")
slp_arr = slp_data.values
bic_scores_slp = {}
sil_scores_slp = {}

for k in range(2, 6):
    km = KMeans(n_clusters=k, random_state=123, n_init=20)
    km.fit(slp_arr)
    bic_scores_slp[k] = compute_bic(km, slp_arr)
    sil_scores_slp[k] = silhouette_score(slp_arr, km.labels_)
    print(f"Groups={k}: BIC={bic_scores_slp[k]:.1f}, Silhouette={sil_scores_slp[k]:.3f}")

best_k_slp = min(bic_scores_slp, key=bic_scores_slp.get)
print(f"\nOptimal Sleep groups: {best_k_slp} (lowest BIC)")

#Don't use
def plot_gbtm_trajectories(data_arr, best_k, variable_name,
                            y_label, y_min, y_max, colours, filename):

    km = KMeans(n_clusters=best_k, random_state=123, n_init=20)
    km.fit(data_arr)

    labels    = km.labels_
    centers   = km.cluster_centers_
    group_counts = pd.Series(labels).value_counts().sort_index()
    group_props  = (group_counts / len(labels) * 100).round(1)

    # Sort groups by mean level (low to high)
    group_order = np.argsort(centers.mean(axis=1))

    fig, ax = plt.subplots(figsize=(9, 6))

    for rank, g in enumerate(group_order):
        label = f"Group {rank+1} ({group_props[g]}%)"
        ax.plot(wave_labels, centers[g],
                color=colours[rank], linewidth=2.2,
                marker='o', markersize=7, label=label)
        for i, (x, y) in enumerate(zip(wave_labels, centers[g])):
            ax.annotate(f'{y:.2f}', (x, y),
                        textcoords="offset points",
                        xytext=(0, 10), ha='center',
                        fontsize=9, color=colours[rank])

    ax.set_title(f'Group-Based Trajectories: {variable_name}',
                 fontsize=14, fontweight='bold')
    ax.set_xlabel('Survey Wave', fontsize=12)
    ax.set_ylabel(y_label, fontsize=12)
    ax.set_ylim(y_min, y_max)
    ax.legend(fontsize=10, loc='upper right',
              framealpha=0.9, edgecolor='lightgrey')
    ax.text(0.5, -0.12,
            f'Understanding Society (UKHLS), 2009-2021 | {best_k}-group solution',
            ha='center', transform=ax.transAxes, fontsize=9, color='grey')
    ax.grid(axis='y', alpha=0.3)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    plt.show()
    print(f"Saved: {filename}")

    return km, group_props

# Plot GHQ trajectories
ghq_colours = ['#3C3489', '#7F77DD', '#CECBF6', '#AFA9EC', '#534AB7']
km_ghq, props_ghq = plot_gbtm_trajectories(
    data_arr      = ghq_arr,
    best_k        = best_k_ghq,
    variable_name = "GHQ-12 General Health",
    y_label       = "GHQ-12 Score (0-36)",
    y_min         = 0,
    y_max         = 36,
    colours       = ghq_colours[:best_k_ghq],
    filename      = "ghq_gbtm_trajectories.png"
)

# Plot Sleep trajectories
slp_colours = ['#0F6E56', '#1D9E75', '#9FE1CB', '#5DCAA5', '#085041']
km_slp, props_slp = plot_gbtm_trajectories(
    data_arr      = slp_arr,
    best_k        = best_k_slp,
    variable_name = "Sleep Quality",
    y_label       = "Sleep Quality Score (1-4)",
    y_min         = 1,
    y_max         = 4,
    colours       = slp_colours[:best_k_slp],
    filename      = "slp_gbtm_trajectories.png"
)

print("\nAll graphs saved successfully")

# Fix AIC comparison
print(f"Linear model log-likelihood: {result_ghq.llf:.1f}")
print(f"Quadratic model log-likelihood: {result_ghq_quad.llf:.1f}")
print(f"Linear model params: {result_ghq.k_fe}")
print(f"Quadratic model params: {result_ghq_quad.k_fe}")
# Lower log-likelihood (less negative) = better fit

# Force 3 group solution for both
best_k_ghq = 3
best_k_slp = 3

print(f"Algorithm suggested k={best_k_ghq} for GHQ, but 3-group solution selected based on interpretability and BIC-silhouette balance")
km_ghq = plot_gbtm_trajectories(
    ghq_arr, best_k_ghq, "GHQ-12 General Health",
    "GHQ-12 Score (0-36)", 0, 36,
    ghq_colours[:best_k_ghq], "ghq_gbtm_3grp.png"
)

km_slp = plot_gbtm_trajectories(
    slp_arr, best_k_slp, "Sleep Quality",
    "Sleep Quality Score (1-4)", 1, 4,
    slp_colours[:best_k_slp], "slp_gbtm_3grp.png"
)

def style_ax(ax):
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.spines['left'].set_color('#CCCCCC')
    ax.spines['bottom'].set_color('#CCCCCC')
    ax.tick_params(colors='#444444', labelsize=10)
    ax.yaxis.grid(True, color='#E8E8E8', linewidth=0.8, zorder=0)
    ax.set_axisbelow(True)
    ax.xaxis.grid(False)

for spine in ['left', 'bottom']:
    ax.spines[spine].set_color('black')
    ax.spines[spine].set_linewidth(0.5)

# ══════════════════════════════════════════════════════════════
# STEP 1 — Run KMeans ONCE with exactly 3 groups
#          Extract cluster centers and proportions
#          DO NOT re-run KMeans inside the plot function
# ══════════════════════════════════════════════════════════════

ghq_cols = ['ghq1','ghq2','ghq3','ghq4','ghq5']
slp_cols = ['slp1','slp2','slp3','slp4','slp5']

ghq_data = wide_data[ghq_cols].dropna()
slp_data = wide_data[slp_cols].dropna()

print(f"GHQ complete cases: {len(ghq_data)}")
print(f"Sleep complete cases: {len(slp_data)}")

# ── GHQ KMeans (3 groups, fixed) ──────────────────────────────
km_ghq = KMeans(n_clusters=3, random_state=123, n_init=20)
km_ghq.fit(ghq_data.values)

ghq_centers = km_ghq.cluster_centers_          # shape (3, 5)
ghq_labels  = km_ghq.labels_
ghq_counts  = pd.Series(ghq_labels).value_counts().sort_index()
ghq_props   = (ghq_counts / len(ghq_labels) * 100).round(1)

# Sort groups low → high by their mean across all waves
ghq_order = np.argsort(ghq_centers.mean(axis=1))   # indices: low, mid, high

print("\nGHQ group centers (sorted low→high):")
for rank, g in enumerate(ghq_order):
    print(f"  Group {rank+1} ({ghq_props[g]}%): "
          f"{[round(v,2) for v in ghq_centers[g]]}")

# ── Sleep KMeans (3 groups, fixed) ────────────────────────────
km_slp = KMeans(n_clusters=3, random_state=123, n_init=20)
km_slp.fit(slp_data.values)

slp_centers = km_slp.cluster_centers_
slp_labels  = km_slp.labels_
slp_counts  = pd.Series(slp_labels).value_counts().sort_index()
slp_props   = (slp_counts / len(slp_labels) * 100).round(1)

slp_order = np.argsort(slp_centers.mean(axis=1))

print("\nSleep group centers (sorted low→high):")
for rank, g in enumerate(slp_order):
    print(f"  Group {rank+1} ({slp_props[g]}%): "
          f"{[round(v,2) for v in slp_centers[g]]}")

# ══════════════════════════════════════════════════════════════
# STEP 2 — Plot GHQ trajectories with TIGHT y-axis
# ══════════════════════════════════════════════════════════════

ghq_colours      = ['#3C3489', '#7F77DD', '#B0AAEE']
ghq_group_names  = ['Low-stable', 'Moderate-stable', 'High-stable']

fig, ax = plt.subplots(figsize=(9, 5.5))

# Collect all plotted y-values to set tight axis afterwards
all_ghq_y = []

for rank, g in enumerate(ghq_order):
    y_vals   = ghq_centers[g]           # the 5 wave means for this group
    prop     = ghq_props[g]
    name     = ghq_group_names[rank]
    colour   = ghq_colours[rank]
    leg_lbl  = f"{name} ({prop}%)"

    all_ghq_y.extend(y_vals)

    ax.plot(x_pos, y_vals,
            color=colour, linewidth=2.2,
            marker='o', markersize=7,
            markerfacecolor=colour, markeredgecolor='white',
            markeredgewidth=1.5,
            label=leg_lbl, zorder=3)

    # Annotate each point
    for xp, yp in zip(x_pos, y_vals):
        ax.annotate(f'{yp:.2f}', xy=(xp, yp),
                    xytext=(0, 10), textcoords='offset points',
                    ha='center', va='bottom',
                    fontsize=9, color=colour, fontweight='semibold')

# ── Tight y-axis: just enough room for annotations ─────────────
y_lo = min(all_ghq_y) - 0.8
y_hi = max(all_ghq_y) + 1.5
ax.set_ylim(y_lo, y_hi)

# Tick every 1 GHQ unit so scale is readable
ax.yaxis.set_major_locator(ticker.MultipleLocator(4))
ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.0f'))

ax.set_xticks(x_pos)
ax.set_xticklabels(wave_labels, fontsize=10, color='#444444')
ax.set_xlim(-0.35, 4.35)

style_ax(ax)


ax.set_xlabel('Survey Wave', fontsize=11, color='#333333', labelpad=8)
ax.set_ylabel('GHQ-12 Score (0–36)', fontsize=11, color='#333333', labelpad=8)

ax.set_title('Group-Based Trajectories: GHQ-12 General Health',
             fontsize=14, fontweight='bold', color='#1A1A1A',
             pad=25, loc='left')

ax.legend(fontsize=9.5, framealpha=0.8,
          edgecolor='#CCCCCC', loc='upper left',  bbox_to_anchor=(0.7,1.3))

fig.text(0.98, 0.02,
         'N = 12,875 | KMeans 3-group solution. \n'
         'Higher scores indicate worse sleep quality.',
         ha='right', va='bottom', fontsize=9, color='#888888')

plt.tight_layout(rect=[0, 0.04, 1, 0.96])
plt.savefig('ghq_gbtm_tight.png', dpi=300, bbox_inches='tight',
            facecolor='white')
plt.show()
print("Saved: ghq_gbtm_tight.png")

# ══════════════════════════════════════════════════════════════
# STEP 3 — Plot Sleep trajectories with TIGHT y-axis
# ══════════════════════════════════════════════════════════════

slp_colours     = ['#0F6E56', '#1D9E75', '#7DD4BA']
slp_group_names = ['Good sleep', 'Moderate sleep', 'Poor sleep']

fig, ax = plt.subplots(figsize=(9, 5.5))

all_slp_y = []

for rank, g in enumerate(slp_order):
    y_vals  = slp_centers[g]
    prop    = slp_props[g]
    name    = slp_group_names[rank]
    colour  = slp_colours[rank]
    leg_lbl = f"{name} ({prop}%)"

    all_slp_y.extend(y_vals)

    ax.plot(x_pos, y_vals,
            color=colour, linewidth=2.2,
            marker='o', markersize=7,
            markerfacecolor=colour, markeredgecolor='white',
            markeredgewidth=1.5,
            label=leg_lbl, zorder=3)

    for xp, yp in zip(x_pos, y_vals):
        ax.annotate(f'{yp:.2f}', xy=(xp, yp),
                    xytext=(0, 10), textcoords='offset points',
                    ha='center', va='bottom',
                    fontsize=9, color=colour, fontweight='semibold')

# ── Tight y-axis for sleep ─────────────────────────────────────
y_lo = min(all_slp_y) - 0.08
y_hi = max(all_slp_y) + 0.18
ax.set_ylim(y_lo, y_hi)

# Tick every 0.1 units — sleep range is small (1–4 but groups are tight)
ax.yaxis.set_major_locator(ticker.MultipleLocator(0.4))
ax.yaxis.set_major_formatter(ticker.FormatStrFormatter('%.1f'))

ax.set_xticks(x_pos)
ax.set_xticklabels(wave_labels, fontsize=10, color='#444444')
ax.set_xlim(-0.35, 4.35)

style_ax(ax)

ax.set_xlabel('Survey Wave', fontsize=11, color='#333333', labelpad=8)
ax.set_ylabel('Sleep Quality Score (1–4)', fontsize=11,
              color='#333333', labelpad=8)

ax.set_title('Group-Based Trajectories: Sleep Quality',
             fontsize=15, fontweight='bold', color='#1A1A1A',
             pad=25, loc='left')


ax.legend(fontsize=9.5, framealpha=0.8,
          edgecolor='#CCCCCC', loc='upper left',  bbox_to_anchor=(0.7,1.3))

fig.text(0.98, 0.02,
         'N = 12,875 | KMeans 3-group solution. \n'
         'Higher scores indicate worse sleep quality.',
         ha='right', va='bottom', fontsize=9, color='#888888')

plt.tight_layout(rect=[0, 0.04, 1, 0.96])
plt.savefig('slp_gbtm_tight.png', dpi=300, bbox_inches='tight',
            facecolor='white')
plt.show()
print("Saved: slp_gbtm_tight.png")

print("\nBoth GBTM graphs saved successfully.")